
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/server
    username: root
    password: Albert@2019
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MYSQL8Dialect
        formal_sql: true
    show-sql: true
